version: '3.3'
services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /go/src/github.com/s10akir/echo-web-app
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: echo
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
